/* L&M Importadora · Catálogo PDF V1.3 */
let lmLastCatalog=null;
const lmPdfMoney=n=>`Bs ${Number(n||0).toFixed(2)}`;
async function lmImageData(src){if(!src)return null;if(src.startsWith('data:image/'))return src;try{const r=await fetch(src);if(!r.ok)return null;const b=await r.blob();return await new Promise((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=no;fr.readAsDataURL(b)})}catch{return null}}
function lmCatalogProducts(){return (state.products||[]).filter(p=>p.catalog!==false)}
async function generateCatalogPDF(){const C=window.jspdf&&window.jspdf.jsPDF;if(!C)return alert('No se pudo cargar el generador PDF.');const products=lmCatalogProducts();if(!products.length)return alert('No hay productos marcados para catálogo.');const doc=new C({unit:'pt',format:'a4'}),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight();const gold=[202,164,76],black=[13,13,15];doc.setFillColor(...black);doc.rect(0,0,W,118,'F');doc.setTextColor(...gold);doc.setFont('helvetica','bold');doc.setFontSize(25);doc.text('L&M IMPORTADORA',40,55);doc.setTextColor(235,235,235);doc.setFontSize(10);doc.text('CATÁLOGO DE PRODUCTOS',40,78);doc.setFont('helvetica','normal');doc.text(new Date().toLocaleDateString('es-BO'),W-40,78,{align:'right'});let y=145;
for(const p of products){if(y>H-185){doc.addPage();y=42}const d=inv(branch(),p.id),imgs=(p.images&&p.images.length?p.images:[p.image]).filter(Boolean).slice(0,3);doc.setDrawColor(220,220,220);doc.roundedRect(34,y,W-68,155,10,10,'S');let x=46;for(let i=0;i<imgs.length;i++){const data=await lmImageData(imgs[i]);if(data){try{doc.addImage(data,data.includes('png')?'PNG':'JPEG',x,y+14,78,78,undefined,'FAST');x+=86}catch{}}}const tx=Math.max(x,140);doc.setTextColor(...black);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(String(p.name||'Producto').slice(0,55),tx,y+31);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(90,90,90);doc.text(`${p.category||'General'}${p.variant?' · '+p.variant:''}${p.code?' · '+p.code:''}`,tx,y+48);const desc=doc.splitTextToSize(String(p.description||''),W-tx-50).slice(0,3);doc.text(desc,tx,y+65);doc.setTextColor(...black);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(`Unitario: ${lmPdfMoney(d.price)}`,tx,y+112);if(d.wholesalePrice)doc.text(`Mayorista: ${lmPdfMoney(d.wholesalePrice)}`,tx+145,y+112);y+=168}
const blob=doc.output('blob'),url=URL.createObjectURL(blob),name=`LM_CATALOGO_${new Date().toISOString().slice(0,10)}.pdf`;lmLastCatalog={blob,url,name};window.open(url,'_blank');return lmLastCatalog}
async function shareCatalogPDF(){if(!lmLastCatalog)await generateCatalogPDF();if(!lmLastCatalog)return;const f=new File([lmLastCatalog.blob],lmLastCatalog.name,{type:'application/pdf'});if(navigator.canShare&&navigator.canShare({files:[f]})){try{return await navigator.share({files:[f],title:'Catálogo L&M Importadora'})}catch{}}const a=document.createElement('a');a.href=lmLastCatalog.url;a.download=lmLastCatalog.name;a.click()}
