/* L&M Importadora · Catálogo PDF V1.3 */
let lmLastCatalog=null;
const lmPdfMoney=n=>`Bs ${Number(n||0).toFixed(2)}`;
async function lmImageData(src){if(!src)return null;if(src.startsWith('data:image/'))return src;try{const r=await fetch(src,{mode:'cors'});if(!r.ok)return null;const b=await r.blob();return await new Promise((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=no;fr.readAsDataURL(b)})}catch{return null}}
function lmCatalogProducts(){return (state.products||[]).filter(p=>{const d=inv(branch(),p.id);return d.catalog_included!==false&&Number(d.stock||0)>0})}
async function generateCatalogPDF(){const C=window.jspdf&&window.jspdf.jsPDF;if(!C)return alert('No se pudo cargar el generador PDF.');const products=lmCatalogProducts();if(!products.length)return alert('No hay productos disponibles marcados para catálogo.');const doc=new C({unit:'pt',format:'a4'}),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight();const gold=[205,171,82],black=[12,12,14],soft=[242,239,229];function header(){doc.setFillColor(...black);doc.rect(0,0,W,112,'F');doc.setTextColor(...gold);doc.setFont('helvetica','bold');doc.setFontSize(24);doc.text('L&M IMPORTADORA',38,49);doc.setTextColor(...soft);doc.setFontSize(9);doc.text('CATÁLOGO COMERCIAL · '+String(branch()).toUpperCase(),38,71);doc.setFont('helvetica','normal');doc.text(new Date().toLocaleDateString('es-BO'),W-38,71,{align:'right'})}header();let y=134;
for(const p of products){if(y>H-202){doc.addPage();header();y=134}const d=inv(branch(),p.id),productImgs=(window.imgs?imgs(p.id):[]).slice(0,3);doc.setDrawColor(214,205,181);doc.setFillColor(252,251,247);doc.roundedRect(32,y,W-64,172,11,11,'FD');let x=44;let shown=0;for(const src of productImgs){const data=await lmImageData(src);if(data){try{doc.addImage(data,data.includes('image/png')?'PNG':'JPEG',x,y+16,74,74,undefined,'FAST');x+=82;shown++}catch{}}}if(!shown){doc.setFillColor(235,231,218);doc.roundedRect(44,y+16,74,74,8,8,'F');doc.setTextColor(150,139,109);doc.setFontSize(20);doc.text('L&M',81,y+59,{align:'center'});x=128}const tx=Math.max(x+4,140);doc.setTextColor(...black);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(String(p.name||'Producto').slice(0,58),tx,y+30);doc.setFont('helvetica','normal');doc.setFontSize(8.8);doc.setTextColor(92,88,78);const meta=[p.category||'General',p.variant,p.brand,p.model,p.code].filter(Boolean).join(' · ');doc.text(meta.slice(0,90),tx,y+47);const desc=doc.splitTextToSize(String(p.description||''),W-tx-48).slice(0,4);doc.text(desc,tx,y+65);doc.setTextColor(...black);doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.text(`Precio unitario: ${lmPdfMoney(d.price)}`,44,y+126);if(Number(d.wholesale_price||0)>0)doc.text(`Mayorista: ${lmPdfMoney(d.wholesale_price)}`,206,y+126);if(Number(d.distributor_price||0)>0)doc.text(`Distribuidor: ${lmPdfMoney(d.distributor_price)}`,355,y+126);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(116,111,99);doc.text(`Disponible · Stock actual: ${Number(d.stock||0)} unidad(es)`,44,y+148);y+=184}
doc.setFontSize(7.5);doc.setTextColor(130,124,111);doc.text('Precios sujetos a disponibilidad y actualización comercial.',W/2,H-18,{align:'center'});const blob=doc.output('blob'),url=URL.createObjectURL(blob),name=`LM_CATALOGO_${String(branch()).replace(/\s+/g,'_')}_${new Date().toISOString().slice(0,10)}.pdf`;if(lmLastCatalog?.url)URL.revokeObjectURL(lmLastCatalog.url);lmLastCatalog={blob,url,name};window.open(url,'_blank');return lmLastCatalog}
async function shareCatalogPDF(){if(!lmLastCatalog)await generateCatalogPDF();if(!lmLastCatalog)return;const f=new File([lmLastCatalog.blob],lmLastCatalog.name,{type:'application/pdf'});if(navigator.canShare&&navigator.canShare({files:[f]})){try{return await navigator.share({files:[f],title:'Catálogo L&M Importadora',text:'Catálogo comercial L&M Importadora'})}catch{}}const a=document.createElement('a');a.href=lmLastCatalog.url;a.download=lmLastCatalog.name;document.body.appendChild(a);a.click();a.remove()}
Object.assign(window,{generateCatalogPDF,shareCatalogPDF});