/* Red L&M · compartir stock por sucursal */
const netDb=window.supabase.createClient(window.LM_CONFIG.SUPABASE_URL,window.LM_CONFIG.SUPABASE_PUBLISHABLE_KEY);
function netBranchName(id){return (window.state?.branches||[]).find(b=>b.id===id)?.name||'Sucursal'}
function netStatus(s){return({pending:'Pendiente',accepted:'En tránsito',received:'Recibido',rejected:'Rechazado',cancelled:'Cancelado'}[s]||s)}
function injectNetworkButton(){const top=document.querySelector('.topbar');if(!top||document.getElementById('lmNetworkBtn')||!window.state?.profile)return;const b=document.createElement('button');b.id='lmNetworkBtn';b.className='netButton';b.innerHTML='◎ <span>Red L&M</span>';b.onclick=openNetworkLM;const profile=top.querySelector('.profile');top.insertBefore(b,profile)}
new MutationObserver(injectNetworkButton).observe(document.documentElement,{childList:true,subtree:true});setTimeout(injectNetworkButton,600);
async function openNetworkLM(){if(!window.state?.profile)return;const me=window.state.profile,own=me.branch_id;const [{data:sharing},{data:inventory},{data:requests}]=await Promise.all([netDb.from('stock_sharing').select('*'),netDb.from('inventory').select('*'),netDb.from('stock_requests').select('*').order('created_at',{ascending:false}).limit(30)]);const others=(window.state.branches||[]).filter(b=>b.id!==own),shareRows=sharing||[],netInv=(inventory||[]).filter(i=>i.branch_id!==own);let html=`<div class="modalback networkOverlay"><div class="modal netPanel"><div class="modalhead"><div><h3>Red L&M</h3><small>Compartir, consultar y transferir stock entre sucursales.</small></div><button class="close" onclick="closeNetworkLM()">×</button></div><div class="sectionhead"><div><h2>Quién puede ver mi inventario</h2><small>Los permisos son opcionales y se pueden cambiar cuando quieras.</small></div></div><div class="shareGrid">${others.map(b=>{const r=shareRows.find(x=>x.owner_branch_id===own&&x.viewer_branch_id===b.id)||{};return `<article class="shareCard"><b>${netBranchName(b.id)}</b><label><input type="checkbox" ${r.can_view_stock?'checked':''} onchange="setNetworkPermission('${b.id}','can_view_stock',this.checked)"> Ver stock</label><label><input type="checkbox" ${r.can_view_price?'checked':''} onchange="setNetworkPermission('${b.id}','can_view_price',this.checked)"> Ver precios</label><label><input type="checkbox" ${r.can_request?'checked':''} onchange="setNetworkPermission('${b.id}','can_request',this.checked)"> Solicitar mercadería</label></article>`}).join('')}</div><div class="sectionhead"><div><h2>Inventarios compartidos conmigo</h2><small>Solo aparecen las sucursales que te dieron permiso.</small></div></div>`;
for(const b of others){const rows=netInv.filter(i=>i.branch_id===b.id),perm=shareRows.find(x=>x.owner_branch_id===b.id&&x.viewer_branch_id===own);if(!rows.length||!perm?.can_view_stock)continue;const units=rows.reduce((a,x)=>a+Number(x.stock||0),0);html+=`<article class="branchCard"><div class="networkHead"><div><b>${netBranchName(b.id)}</b><small>${units} unidades visibles</small></div><span class="pill">Compartido</span></div><div class="netProducts">${rows.filter(x=>x.stock>0).slice(0,8).map(i=>{const p=(window.state.products||[]).find(x=>x.id===i.product_id);if(!p)return'';const pic=window.imgs?imgs(p.id)[0]:'';return `<div class="netProduct"><div class="netThumb">${pic?`<img src="${pic}">`:'📦'}</div><div><b>${p.name}</b><small>${p.variant||p.code||''}</small></div><div class="netStock"><strong>${i.stock}</strong><small>${perm.can_view_price?`Unit. ${moneyNet(i.price)}`:'Precio privado'}</small></div>${perm.can_request?`<button class="miniBtn" onclick="requestNetworkStock('${b.id}','${p.id}',${i.stock})">Solicitar</button>`:''}</div>`}).join('')||'<div class="empty compact">Sin unidades disponibles.</div>'}</div></article>`}
const rel=(requests||[]);html+=`<div class="sectionhead"><div><h2>Solicitudes y envíos</h2><small>Flujo: solicitar → aceptar → en tránsito → recibir.</small></div></div><div class="requestList">${rel.map(r=>{const p=(window.state.products||[]).find(x=>x.id===r.product_id);const incoming=r.to_branch_id===own,outgoing=r.from_branch_id===own;let actions='';if(incoming&&r.status==='pending')actions=`<div class="requestActions"><button class="miniBtn" onclick="acceptNetworkRequest('${r.id}')">Aceptar</button><button class="miniBtn dangerMini" onclick="rejectNetworkRequest('${r.id}')">Rechazar</button></div>`;if(outgoing&&r.status==='accepted')actions=`<div class="requestActions"><button class="miniBtn" onclick="receiveNetworkRequest('${r.id}')">Confirmar recepción</button></div>`;return `<div class="requestCard"><div><b>${p?.name||'Producto'}</b><small>${incoming?'Solicitud de '+netBranchName(r.from_branch_id):'Pedido a '+netBranchName(r.to_branch_id)} · ${r.quantity} un.</small><em>${netStatus(r.status)}</em></div><div class="requestSide"><span class="pill status-${r.status}">${netStatus(r.status)}</span>${actions}</div></div>`}).join('')||'<div class="empty compact">Sin solicitudes todavía.</div>'}</div></div></div>`;let root=document.getElementById('network-root');if(!root){root=document.createElement('div');root.id='network-root';document.body.appendChild(root)}root.innerHTML=html}
function moneyNet(n){return `Bs ${Number(n||0).toFixed(2)}`}
function closeNetworkLM(){document.getElementById('network-root')?.remove()}
async function setNetworkPermission(viewer,field,value){const own=window.state.profile.branch_id;const {data:existing}=await netDb.from('stock_sharing').select('*').eq('owner_branch_id',own).eq('viewer_branch_id',viewer).maybeSingle();const payload={owner_branch_id:own,viewer_branch_id:viewer,can_view_stock:existing?.can_view_stock||false,can_view_price:existing?.can_view_price||false,can_request:existing?.can_request||false,[field]:value};if(field==='can_view_stock'&&!value){payload.can_view_price=false;payload.can_request=false}const {error}=await netDb.from('stock_sharing').upsert(payload,{onConflict:'owner_branch_id,viewer_branch_id'});if(error)return alert(error.message);openNetworkLM()}
async function requestNetworkStock(ownerBranch,productId,maxStock){const raw=prompt(`¿Cuántas unidades quieres solicitar? Disponible: ${maxStock}`,'1');if(raw===null)return;const quantity=Math.max(1,Math.min(maxStock,parseInt(raw||'1')));const own=window.state.profile.branch_id;const {error}=await netDb.from('stock_requests').insert({from_branch_id:own,to_branch_id:ownerBranch,product_id:productId,quantity,status:'pending',requested_by:window.state.user.id});if(error)return alert(error.message);openNetworkLM()}
async function acceptNetworkRequest(id){const {error}=await netDb.rpc('accept_stock_request',{p_request:id});if(error)return alert(error.message);if(window.loadAll)await loadAll();openNetworkLM()}
async function rejectNetworkRequest(id){const {error}=await netDb.rpc('reject_stock_request',{p_request:id});if(error)return alert(error.message);openNetworkLM()}
async function receiveNetworkRequest(id){const {error}=await netDb.rpc('receive_stock_request',{p_request:id});if(error)return alert(error.message);if(window.loadAll)await loadAll();openNetworkLM()}
Object.assign(window,{openNetworkLM,closeNetworkLM,setNetworkPermission,requestNetworkStock,acceptNetworkRequest,rejectNetworkRequest,receiveNetworkRequest});