const CFG=window.LM_CONFIG||{};
const db=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY);
const state={session:null,user:null,profile:null,branches:[],products:[],inventory:[],images:[],sales:[],imports:[],importItems:[],view:'Inicio',search:'',cart:{},modal:''};
const app=document.getElementById('app');
const money=n=>`Bs ${Number(n||0).toFixed(2)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const byId=id=>document.getElementById(id);
const num=v=>Math.max(0,Number(v||0));
const me=()=>state.profile;
const branch=()=>state.profile?.branches?.name||'Sin sucursal';
const branchId=()=>state.profile?.branch_id||null;
function inv(_b,id){return state.inventory.find(x=>x.product_id===id)||{stock:0,cost:0,cost_origin:0,logistics_cost:0,duty_cost:0,other_cost:0,price:0,wholesale_price:0,distributor_price:0,catalog_included:true}}
function imgs(id){return state.images.filter(x=>x.product_id===id).sort((a,b)=>a.sort_order-b.sort_order).map(x=>x.image_url)}
function primaryImg(p){return imgs(p.id)[0]||p.image_path||''}
function landed(d){return num(d.cost_origin)+num(d.logistics_cost)+num(d.duty_cost)+num(d.other_cost)}
function profitAt(price,d){return num(price)-landed(d)}
function marginAt(price,d){price=num(price);return price?profitAt(price,d)/price*100:0}
function stockValue(){return state.products.reduce((a,p)=>{const d=inv(branch(),p.id);return a+d.stock*landed(d)},0)}
function potentialProfit(){return state.products.reduce((a,p)=>{const d=inv(branch(),p.id);return a+d.stock*profitAt(d.price,d)},0)}
function activeProducts(){const q=state.search.trim().toLowerCase();return state.products.filter(p=>!q||[p.name,p.variant,p.code,p.description,p.category,p.brand,p.model].join(' ').toLowerCase().includes(q))}
function toast(msg,type='ok'){let t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2800)}

async function init(){const {data:{session}}=await db.auth.getSession();state.session=session;state.user=session?.user||null;await loadBranches();if(state.user){await loadProfile();if(state.profile)await loadAll()}db.auth.onAuthStateChange(async(_e,s)=>{state.session=s;state.user=s?.user||null;if(state.user){await loadProfile();if(state.profile)await loadAll()}else{state.profile=null;state.products=[];state.inventory=[];state.images=[]}render()});render()}
async function loadBranches(){const {data}=await db.from('branches').select('id,name').eq('active',true).order('name');state.branches=data||[]}
async function loadProfile(){const {data,error}=await db.from('profiles').select('id,display_name,role,branch_id,must_change_password,branches(name)').eq('id',state.user.id).maybeSingle();if(error)console.error(error);state.profile=data||null}
async function loadAll(){await Promise.all([loadProducts(),loadInventory(),loadImages(),loadSales(),loadImports()])}
async function loadProducts(){const {data,error}=await db.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(error)console.error(error);state.products=data||[]}
async function loadInventory(){if(!branchId())return;const {data,error}=await db.from('inventory').select('*').eq('branch_id',branchId());if(error)console.error(error);state.inventory=data||[]}
async function loadImages(){const {data,error}=await db.from('product_images').select('*').order('sort_order');if(error)console.error(error);state.images=data||[]}
async function loadSales(){if(!branchId())return;const {data,error}=await db.from('sales').select('*').eq('branch_id',branchId()).order('created_at',{ascending:false}).limit(100);if(error)console.error(error);state.sales=data||[]}
async function loadImports(){if(!branchId())return;const {data,error}=await db.from('import_batches').select('*').eq('branch_id',branchId()).order('created_at',{ascending:false});if(error)console.error(error);state.imports=data||[];if(state.imports.length){const ids=state.imports.map(x=>x.id);const r=await db.from('import_batch_items').select('*').in('batch_id',ids);state.importItems=r.data||[]}else state.importItems=[]}

function authScreen(){app.innerHTML=`<div class="authWrap"><div class="authCard"><section class="authBrand"><div class="logo big">L&M</div><div class="eyebrow">IMPORTADORA L&M</div><h1>Inventario, ventas e importaciones en un solo lugar.</h1><p>Un sistema privado para controlar productos, costos reales, márgenes, stock por ciudad y catálogos comerciales.</p><div class="authPoints"><span>◆ 3 imágenes por producto</span><span>◆ Precio unitario, mayorista y distribuidor</span><span>◆ Costos de importación y utilidad real</span></div></section><section class="authForm"><div class="authTabs"><button class="active" id="loginTab" onclick="showLogin()">Ingresar</button><button id="signupTab" onclick="showSignup()">Crear cuenta</button></div><div id="authBody">${loginForm()}</div></section></div></div>`}
function loginForm(){return `<h2>Bienvenido</h2><p class="muted">Ingresa con tu correo y contraseña.</p><div class="field"><label>Correo</label><input id="email" type="email" placeholder="correo@gmail.com"></div><div class="field"><label>Contraseña</label><input id="password" type="password" placeholder="••••••••"></div><button class="btn primary block" onclick="signIn()">Ingresar</button>`}
function signupForm(){return `<h2>Crear cuenta</h2><p class="muted">Laura, Sergio u otro integrante puede crear su propio acceso.</p><div class="field"><label>Correo</label><input id="email" type="email" placeholder="correo@gmail.com"></div><div class="field"><label>Contraseña</label><input id="password" type="password" minlength="6"></div><div class="field"><label>Repetir contraseña</label><input id="password2" type="password" minlength="6"></div><button class="btn primary block" onclick="signUp()">Crear mi cuenta</button>`}
function showLogin(){byId('authBody').innerHTML=loginForm();byId('loginTab').classList.add('active');byId('signupTab').classList.remove('active')}
function showSignup(){byId('authBody').innerHTML=signupForm();byId('signupTab').classList.add('active');byId('loginTab').classList.remove('active')}
async function signIn(){const email=byId('email').value.trim(),password=byId('password').value;if(!email||!password)return toast('Completa correo y contraseña','error');const {error}=await db.auth.signInWithPassword({email,password});if(error)toast(error.message,'error')}
async function signUp(){const email=byId('email').value.trim(),password=byId('password').value,p2=byId('password2').value;if(password!==p2)return toast('Las contraseñas no coinciden','error');const {data,error}=await db.auth.signUp({email,password});if(error)return toast(error.message,'error');if(!data.session)toast('Cuenta creada. Revisa tu correo para confirmar el acceso.');else toast('Cuenta creada correctamente')}
async function logout(){await db.auth.signOut()}

function profileSetup(){app.innerHTML=`<div class="authWrap"><div class="setupCard"><div class="eyebrow">CONFIGURACIÓN INICIAL</div><h1>Crea tu perfil interno</h1><p class="muted">Tu cuenta ya está registrada. Elige cómo aparecerás dentro de L&M.</p><div class="field"><label>Nombre visible</label><input id="displayName" placeholder="Ej. Laura"></div><div class="field"><label>Sucursal principal</label><select id="branchSelect"><option value="">Seleccionar...</option>${state.branches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></div><button class="btn primary block" onclick="saveProfile()">Guardar y entrar</button><button class="btn secondary block" style="margin-top:8px" onclick="logout()">Cerrar sesión</button></div></div>`}
async function saveProfile(){const display_name=byId('displayName').value.trim(),branch_id=byId('branchSelect').value;if(!display_name||!branch_id)return toast('Completa nombre y sucursal','error');const {error}=await db.from('profiles').insert({id:state.user.id,display_name,branch_id,role:'manager',must_change_password:false});if(error)return toast(error.message,'error');await loadProfile();await loadAll();render()}

const navItems=[['Inicio','⌂'],['Inventario','▣'],['Ventas','🛒'],['Importaciones','⇣'],['Catálogo','▤'],['Ajustes','⚙']];
function shell(){app.innerHTML=`<header class="topbar"><div class="brand"><div class="logo">L&M</div><div><strong>Importadora</strong><small>Inventario · Ventas · Importaciones</small></div></div><div class="profile"><small>${esc(branch())}</small><b>${esc(me().display_name)}</b></div></header><main id="content"></main><nav id="nav">${navItems.map(([v,i])=>`<button class="${state.view===v?'active':''}" onclick="go('${v}')">${i}<span>${v}</span></button>`).join('')}</nav><div id="modal"></div>`;renderView()}
function go(v){state.view=v;state.search='';state.modal='';shell()}
function searchBox(){return `<div class="toolbar"><div class="search"><input placeholder="Buscar nombre, variante, código, marca..." value="${esc(state.search)}" oninput="state.search=this.value;renderView()"></div></div>`}
function hero(title,sub,actions=''){return `<section class="hero"><div><small>L&M IMPORTADORA · V${esc(CFG.VERSION||'1.3')}</small><h1>${title}</h1><p>${sub}</p></div><div class="heroActions">${actions}</div></section>`}
function thumb(p){const src=primaryImg(p);return `<div class="thumb">${src?`<img src="${esc(src)}" alt="">`:'📦'}</div>`}
function productRow(p,mode='normal'){const d=inv(branch(),p.id);return `<article class="product ${mode==='sale'?'clickable':''}" ${mode==='sale'?`onclick="addCart('${p.id}')"`:''}>${thumb(p)}<div class="info"><b>${esc(p.name)}</b><span>${esc(p.variant||p.category||'General')}</span><small>${esc(p.code||'')} ${p.brand?'· '+esc(p.brand):''}</small></div><div class="numbers"><b>${money(d.price)}</b><span class="${d.stock<=3?'low':''}">${d.stock} un.</span>${mode==='cost'?`<small>Puesto ${money(landed(d))}</small>`:''}</div>${mode==='edit'?`<button class="miniBtn" onclick="event.stopPropagation();openProduct('${p.id}')">Editar</button>`:''}</article>`}

function renderView(){const c=byId('content');if(!c)return;const ps=activeProducts();
if(state.view==='Inicio'){const units=state.inventory.reduce((a,x)=>a+num(x.stock),0),today=new Date().toISOString().slice(0,10),todaySales=state.sales.filter(s=>s.created_at?.slice(0,10)===today).reduce((a,s)=>a+num(s.total),0);c.innerHTML=hero(`Hola, ${esc(me().display_name)}`,`${esc(branch())} · Control comercial y financiero`, `<button class="btn primary" onclick="go('Ventas')">+ Nueva venta</button>`)+`<div class="stats"><div class="stat"><span>Stock total</span><b>${units}</b><small>unidades</small></div><div class="stat"><span>Ventas hoy</span><b>${money(todaySales)}</b><small>registradas</small></div><div class="stat"><span>Capital en stock</span><b>${money(stockValue())}</b><small>costo puesto</small></div><div class="stat"><span>Utilidad potencial</span><b>${money(potentialProfit())}</b><small>a precio unitario</small></div></div><div class="sectionhead"><div><h2>Productos recientes</h2><small>Vista rápida de tu inventario</small></div></div><div class="products">${state.products.slice(0,6).map(p=>productRow(p)).join('')||'<div class="empty">Aún no hay productos.</div>'}</div>`}
if(state.view==='Inventario')c.innerHTML=hero('Mi inventario',`${esc(branch())} · Productos genéricos, variantes, fotos y precios`,`<button class="btn primary" onclick="openProduct()">+ Producto</button>`)+searchBox()+`<div class="products">${ps.map(p=>productRow(p,'edit')).join('')||'<div class="empty">No hay productos registrados.</div>'}</div>`;
if(state.view==='Ventas')renderSales(c,ps);
if(state.view==='Importaciones')renderImports(c);
if(state.view==='Catálogo')renderCatalog(c,ps);
if(state.view==='Ajustes')renderSettings(c);
}

function renderSales(c,ps){const total=Object.entries(state.cart).reduce((a,[id,q])=>a+num(inv(branch(),id).price)*q,0);c.innerHTML=hero('Nueva venta',`${esc(branch())} · Selecciona los productos visualmente`)+`<div class="grid2"><section>${searchBox()}<div class="products">${ps.map(p=>productRow(p,'sale')).join('')||'<div class="empty">No hay productos.</div>'}</div></section><aside class="card sticky"><h3>Carrito</h3>${Object.entries(state.cart).map(([id,q])=>{const p=state.products.find(x=>x.id===id),d=inv(branch(),id);return `<div class="cartrow"><div><b>${esc(p?.name||'Producto')}</b><small>${esc(p?.variant||'')}</small></div><div class="qty"><button onclick="changeQty('${id}',-1)">−</button> ${q} <button onclick="changeQty('${id}',1)">+</button></div><b>${money(d.price*q)}</b></div>`}).join('')||'<div class="empty compact">Añade productos.</div>'}<div class="field"><label>Cliente (opcional)</label><input id="customer" placeholder="Nombre"></div><div class="field"><label>Forma de pago</label><select id="payment"><option value="cash">Efectivo</option><option value="qr">QR</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></div><div class="costline total"><span>Total</span><b>${money(total)}</b></div><button class="btn primary block" ${!total?'disabled':''} onclick="completeSale()">Confirmar venta</button></aside></div>`}
function addCart(id){const d=inv(branch(),id);if(d.stock<1)return toast('Producto sin stock','error');state.cart[id]=Math.min((state.cart[id]||0)+1,d.stock);renderView()}
function changeQty(id,n){state.cart[id]=(state.cart[id]||0)+n;if(state.cart[id]<=0)delete state.cart[id];else state.cart[id]=Math.min(state.cart[id],inv(branch(),id).stock);renderView()}
async function completeSale(){const entries=Object.entries(state.cart);if(!entries.length)return;for(const [id,q] of entries)if(q>inv(branch(),id).stock)return toast('Stock insuficiente','error');const subtotal=entries.reduce((a,[id,q])=>a+inv(branch(),id).price*q,0);const {data:sale,error}=await db.from('sales').insert({branch_id:branchId(),seller_id:state.user.id,customer_name:byId('customer')?.value||null,payment_method:byId('payment')?.value||'cash',subtotal,discount:0,total:subtotal}).select('id').single();if(error)return toast(error.message,'error');for(const [id,q] of entries){const d=inv(branch(),id);const p=state.products.find(x=>x.id===id);await db.from('sale_items').insert({sale_id:sale.id,product_id:id,quantity:q,unit_price:d.price,unit_cost:landed(d)});await db.from('inventory').update({stock:d.stock-q,updated_at:new Date().toISOString()}).eq('branch_id',branchId()).eq('product_id',id);await db.from('inventory_movements').insert({branch_id:branchId(),product_id:id,user_id:state.user.id,movement_type:'sale',quantity:-q,reference_id:sale.id,note:`Venta ${p?.name||''}`})}state.cart={};await Promise.all([loadInventory(),loadSales()]);toast('Venta registrada correctamente');renderView()}

function renderImports(c){const cards=state.imports.map(b=>{const items=state.importItems.filter(i=>i.batch_id===b.id),units=items.reduce((a,i)=>a+i.quantity,0),landedTotal=items.reduce((a,i)=>a+i.landed_unit_cost_bs*i.quantity,0);return `<article class="importCard"><div class="importTop"><div><span class="pill">${esc(b.status)}</span><h3>${esc(b.reference)}</h3><small>${esc(b.supplier||'Sin proveedor')} ${b.origin_country?'· '+esc(b.origin_country):''}</small></div><div class="numbers"><b>${units} un.</b><small>${money(landedTotal)}</small></div></div><div class="importMeta"><span>Flete ${money(b.freight_total_bs)}</span><span>Aduana ${money(b.duty_total_bs)}</span><span>Logística ${money(b.internal_logistics_bs)}</span><span>Otros ${money(b.other_total_bs)}</span></div><div class="heroActions"><button class="btn secondary" onclick="openImportItem('${b.id}')">+ Producto</button>${b.status!=='received'?`<button class="btn primary" onclick="receiveImport('${b.id}')" ${!items.length?'disabled':''}>Recibir importación</button>`:''}</div></article>`}).join('');c.innerHTML=hero('Importaciones','Registra cada llegada, reparte gastos y calcula el costo puesto en Bolivia.',`<button class="btn primary" onclick="openImport()">+ Importación</button>`)+`<div class="notice">Los gastos comunes se distribuyen proporcionalmente al valor de compra de cada producto. Al marcar una importación como recibida, el stock y el costo promedio se actualizan automáticamente.</div><div class="importList">${cards||'<div class="empty">Todavía no registraste importaciones.</div>'}</div>`}
function openImport(){state.modal='import';byId('modal').innerHTML=`<div class="modalback"><div class="modal"><div class="modalhead"><h3>Nueva importación</h3><button class="close" onclick="closeModal()">×</button></div><div class="grid2"><div class="field"><label>Referencia</label><input id="iref" placeholder="IMP-2026-001"></div><div class="field"><label>Proveedor</label><input id="isupplier"></div><div class="field"><label>País de origen</label><input id="icountry" placeholder="China"></div><div class="field"><label>Moneda</label><select id="icurrency"><option>USD</option><option>BOB</option><option>CNY</option><option>EUR</option></select></div><div class="field"><label>Tipo de cambio a Bs</label><input id="iexchange" type="number" step="0.0001" value="6.96"></div><div class="field"><label>Estado</label><select id="istatus"><option value="draft">Borrador</option><option value="in_transit">En tránsito</option></select></div></div><div class="grid2"><div class="field"><label>Flete total Bs</label><input id="ifreight" type="number" step="0.01" value="0"></div><div class="field"><label>Aduana/impuestos Bs</label><input id="iduty" type="number" step="0.01" value="0"></div><div class="field"><label>Logística interna Bs</label><input id="iinternal" type="number" step="0.01" value="0"></div><div class="field"><label>Otros gastos Bs</label><input id="iother" type="number" step="0.01" value="0"></div></div><div class="field"><label>Notas</label><textarea id="inotes" rows="3"></textarea></div><button class="btn primary block" onclick="saveImport()">Guardar importación</button></div></div>`}
async function saveImport(){const reference=byId('iref').value.trim();if(!reference)return toast('La referencia es obligatoria','error');const payload={branch_id:branchId(),reference,supplier:byId('isupplier').value.trim()||null,origin_country:byId('icountry').value.trim()||null,currency:byId('icurrency').value,exchange_rate:num(byId('iexchange').value)||1,freight_total_bs:num(byId('ifreight').value),duty_total_bs:num(byId('iduty').value),internal_logistics_bs:num(byId('iinternal').value),other_total_bs:num(byId('iother').value),status:byId('istatus').value,notes:byId('inotes').value.trim()||null,created_by:state.user.id};const {error}=await db.from('import_batches').insert(payload);if(error)return toast(error.message,'error');closeModal();await loadImports();toast('Importación creada');renderView()}
function openImportItem(batchId){const b=state.imports.find(x=>x.id===batchId);if(!b)return;byId('modal').innerHTML=`<div class="modalback"><div class="modal"><div class="modalhead"><h3>Agregar producto · ${esc(b.reference)}</h3><button class="close" onclick="closeModal()">×</button></div><div class="field"><label>Producto</label><select id="iiProduct"><option value="">Seleccionar...</option>${state.products.map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.variant||p.code||'')}</option>`).join('')}</select></div><div class="grid2"><div class="field"><label>Cantidad</label><input id="iiQty" type="number" min="1" value="1"></div><div class="field"><label>Costo unitario (${esc(b.currency)})</label><input id="iiCost" type="number" step="0.0001" value="0"></div></div><button class="btn primary block" onclick="saveImportItem('${batchId}')">Agregar y recalcular</button></div></div>`}
async function saveImportItem(batchId){const b=state.imports.find(x=>x.id===batchId),product_id=byId('iiProduct').value,quantity=Math.max(1,parseInt(byId('iiQty').value||1)),unit_cost_foreign=num(byId('iiCost').value);if(!product_id)return toast('Selecciona un producto','error');const unit_origin_bs=unit_cost_foreign*num(b.exchange_rate);const {error}=await db.from('import_batch_items').insert({batch_id:batchId,product_id,quantity,unit_cost_foreign,unit_origin_bs,landed_unit_cost_bs:unit_origin_bs});if(error)return toast(error.message,'error');await recalcImport(batchId);closeModal();await loadImports();toast('Producto agregado a la importación');renderView()}
async function recalcImport(batchId){const b=state.imports.find(x=>x.id===batchId);const {data:items}=await db.from('import_batch_items').select('*').eq('batch_id',batchId);if(!items?.length)return;const base=items.reduce((a,i)=>a+i.unit_origin_bs*i.quantity,0)||items.reduce((a,i)=>a+i.quantity,0);for(const i of items){const line=i.unit_origin_bs*i.quantity,share=base?(line||i.quantity)/base:1/items.length,freight=((num(b.freight_total_bs)+num(b.internal_logistics_bs))*share)/i.quantity,duty=(num(b.duty_total_bs)*share)/i.quantity,other=(num(b.other_total_bs)*share)/i.quantity,landedUnit=i.unit_origin_bs+freight+duty+other;await db.from('import_batch_items').update({allocated_freight_bs:freight,allocated_duty_bs:duty,allocated_other_bs:other,landed_unit_cost_bs:landedUnit}).eq('id',i.id)}}
async function receiveImport(batchId){const b=state.imports.find(x=>x.id===batchId);if(!b||b.status==='received')return;await recalcImport(batchId);const {data:items,error}=await db.from('import_batch_items').select('*').eq('batch_id',batchId);if(error||!items?.length)return toast('No hay productos para recibir','error');for(const i of items){let d=inv(branch(),i.product_id),old=num(d.stock),qty=num(i.quantity),tot=old+qty;const w=(oldVal,newVal)=>(oldVal*old+newVal*qty)/tot;const origin=w(num(d.cost_origin),num(i.unit_origin_bs)),freight=w(num(d.logistics_cost),num(i.allocated_freight_bs)),duty=w(num(d.duty_cost),num(i.allocated_duty_bs)),other=w(num(d.other_cost),num(i.allocated_other_bs));const payload={branch_id:branchId(),product_id:i.product_id,stock:tot,cost_origin:origin,logistics_cost:freight,duty_cost:duty,other_cost:other,cost:origin+freight+duty+other,price:num(d.price),wholesale_price:num(d.wholesale_price),distributor_price:num(d.distributor_price),catalog_included:d.catalog_included!==false,updated_at:new Date().toISOString()};const {error:e}=await db.from('inventory').upsert(payload,{onConflict:'branch_id,product_id'});if(e)return toast(e.message,'error');await db.from('inventory_movements').insert({branch_id:branchId(),product_id:i.product_id,user_id:state.user.id,movement_type:'entry',quantity:qty,reference_id:batchId,note:`Importación ${b.reference}`})}await db.from('import_batches').update({status:'received',received_date:new Date().toISOString().slice(0,10)}).eq('id',batchId);await Promise.all([loadInventory(),loadImports()]);toast('Importación recibida y stock actualizado');renderView()}

function renderCatalog(c,ps){const included=ps.filter(p=>inv(branch(),p.id).catalog_included!==false),available=included.filter(p=>inv(branch(),p.id).stock>0);c.innerHTML=hero('Catálogo PDF','Marca qué productos entran al catálogo comercial y genera un PDF listo para compartir.',`<button class="btn primary" onclick="generateCatalogPDF()">Generar PDF</button><button class="btn secondary" onclick="shareCatalogPDF()">Compartir</button>`)+`<div class="stats"><div class="stat"><span>Incluidos</span><b>${included.length}</b><small>productos</small></div><div class="stat"><span>Disponibles</span><b>${available.length}</b><small>con stock</small></div><div class="stat"><span>Fotos</span><b>${state.images.length}</b><small>almacenadas</small></div><div class="stat"><span>Sucursal</span><b>${esc(branch())}</b><small>catálogo actual</small></div></div><div class="products">${ps.map(p=>{const d=inv(branch(),p.id);return `<article class="catalogRow">${thumb(p)}<div class="info"><b>${esc(p.name)}</b><span>${esc(p.variant||p.category||'General')}</span><small>${imgs(p.id).length}/3 imágenes · ${d.stock} un.</small></div><div class="catalogPrices"><b>${money(d.price)}</b><small>Mayorista ${money(d.wholesale_price)}</small></div><label class="switch"><input type="checkbox" ${d.catalog_included!==false?'checked':''} onchange="toggleCatalog('${p.id}',this.checked)"><span></span></label></article>`}).join('')||'<div class="empty">No hay productos.</div>'}</div>`}
async function toggleCatalog(productId,val){const d=inv(branch(),productId);const payload={branch_id:branchId(),product_id:productId,stock:num(d.stock),cost:num(d.cost),cost_origin:num(d.cost_origin),logistics_cost:num(d.logistics_cost),duty_cost:num(d.duty_cost),other_cost:num(d.other_cost),price:num(d.price),wholesale_price:num(d.wholesale_price),distributor_price:num(d.distributor_price),catalog_included:val,updated_at:new Date().toISOString()};const {error}=await db.from('inventory').upsert(payload,{onConflict:'branch_id,product_id'});if(error)return toast(error.message,'error');await loadInventory();renderView()}

function renderSettings(c){c.innerHTML=hero('Configuración',`${esc(me().display_name)} · ${esc(branch())}`)+`<div class="grid2"><div class="card"><h3>Mi perfil</h3><div class="costline"><span>Correo</span><b>${esc(state.user.email||'')}</b></div><div class="costline"><span>Rol</span><b>${esc(me().role)}</b></div><div class="costline"><span>Sucursal</span><b>${esc(branch())}</b></div><button class="btn secondary block" onclick="logout()">Cerrar sesión</button></div><div class="card"><h3>Versión</h3><p class="muted">L&M Importadora V${esc(CFG.VERSION||'1.3.0')}</p><p class="muted">Supabase conectado · GitHub Pages · Catálogo PDF · Importaciones.</p><button class="btn primary block" onclick="loadAll().then(renderView)">Sincronizar ahora</button></div></div>`}

function openProduct(id=''){const p=id?state.products.find(x=>x.id===id):null,d=p?inv(branch(),id):inv(branch(),'');const im=p?imgs(p.id):[];byId('modal').innerHTML=`<div class="modalback"><div class="modal"><div class="modalhead"><div><h3>${p?'Editar producto':'Nuevo producto'}</h3><small>Hasta tres fotografías por producto.</small></div><button class="close" onclick="closeModal()">×</button></div><div class="grid2"><section><div class="field"><label>Nombre</label><input id="pname" value="${esc(p?.name||'')}"></div><div class="field"><label>Variante</label><input id="pvariant" value="${esc(p?.variant||'')}"></div><div class="field"><label>Categoría</label><input id="pcategory" value="${esc(p?.category||'General')}"></div><div class="field"><label>Marca</label><input id="pbrand" value="${esc(p?.brand||'')}"></div><div class="field"><label>Modelo</label><input id="pmodel" value="${esc(p?.model||'')}"></div><div class="field"><label>Código / SKU</label><input id="pcode" value="${esc(p?.code||'')}"></div><div class="field"><label>Descripción</label><textarea id="pdesc" rows="4">${esc(p?.description||'')}</textarea></div></section><section><div class="photoGrid">${[0,1,2].map(i=>`<label class="photoSlot"><div>${im[i]?`<img src="${esc(im[i])}">`:`<span>📷</span><small>Imagen ${i+1}</small>`}</div><input id="photo${i+1}" type="file" accept="image/*" capture="environment"></label>`).join('')}</div><div class="field"><label>Stock</label><input id="pstock" type="number" min="0" value="${d.stock||0}"></div><div class="grid2"><div class="field"><label>Costo origen</label><input id="porigin" type="number" step="0.01" value="${d.cost_origin||0}"></div><div class="field"><label>Flete/logística</label><input id="plog" type="number" step="0.01" value="${d.logistics_cost||0}"></div><div class="field"><label>Aduana/impuestos</label><input id="pduty" type="number" step="0.01" value="${d.duty_cost||0}"></div><div class="field"><label>Otros gastos</label><input id="pother" type="number" step="0.01" value="${d.other_cost||0}"></div></div><div class="grid3"><div class="field"><label>Precio unitario</label><input id="pprice" type="number" step="0.01" value="${d.price||0}"></div><div class="field"><label>Mayorista</label><input id="pwholesale" type="number" step="0.01" value="${d.wholesale_price||0}"></div><div class="field"><label>Distribuidor</label><input id="pdistributor" type="number" step="0.01" value="${d.distributor_price||0}"></div></div><label class="check"><input id="pcatalog" type="checkbox" ${d.catalog_included!==false?'checked':''}> Incluir en catálogo PDF</label></section></div><button class="btn primary block" onclick="saveProduct('${id}')">Guardar producto</button></div></div>`}
async function compressImage(file){return await new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(url);b?resolve(b):reject(new Error('No se pudo procesar imagen'))},'image/jpeg',.84)};img.onerror=reject;img.src=url})}
async function uploadProductImage(productId,file,order){const blob=await compressImage(file),path=`${state.user.id}/${productId}/${Date.now()}-${order}.jpg`;const {error}=await db.storage.from('product-images').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(error)throw error;const {data}=db.storage.from('product-images').getPublicUrl(path);const image_url=data.publicUrl;const old=state.images.find(x=>x.product_id===productId&&x.sort_order===order);if(old)await db.from('product_images').update({image_url,created_by:state.user.id}).eq('id',old.id);else await db.from('product_images').insert({product_id:productId,image_url,sort_order:order,created_by:state.user.id});return image_url}
async function saveProduct(id=''){const product={name:byId('pname').value.trim(),variant:byId('pvariant').value.trim()||null,category:byId('pcategory').value.trim()||'General',brand:byId('pbrand').value.trim()||null,model:byId('pmodel').value.trim()||null,code:byId('pcode').value.trim(),description:byId('pdesc').value.trim()||null,active:true,created_by:id?(state.products.find(x=>x.id===id)?.created_by||state.user.id):state.user.id};if(!product.name||!product.code)return toast('Nombre y código son obligatorios','error');let productId=id;if(id){const {error}=await db.from('products').update(product).eq('id',id);if(error)return toast(error.message,'error')}else{const {data,error}=await db.from('products').insert(product).select('id').single();if(error)return toast(error.message,'error');productId=data.id}const cost_origin=num(byId('porigin').value),logistics_cost=num(byId('plog').value),duty_cost=num(byId('pduty').value),other_cost=num(byId('pother').value),cost=cost_origin+logistics_cost+duty_cost+other_cost;const inventory={branch_id:branchId(),product_id:productId,stock:Math.floor(num(byId('pstock').value)),cost,cost_origin,logistics_cost,duty_cost,other_cost,price:num(byId('pprice').value),wholesale_price:num(byId('pwholesale').value),distributor_price:num(byId('pdistributor').value),catalog_included:byId('pcatalog').checked,updated_at:new Date().toISOString()};const {error:ierr}=await db.from('inventory').upsert(inventory,{onConflict:'branch_id,product_id'});if(ierr)return toast(ierr.message,'error');try{for(let i=1;i<=3;i++){const f=byId(`photo${i}`).files?.[0];if(f)await uploadProductImage(productId,f,i)}}catch(e){toast(`Producto guardado, pero una imagen falló: ${e.message}`,'error')}closeModal();await Promise.all([loadProducts(),loadInventory(),loadImages()]);toast('Producto guardado');renderView()}
function closeModal(){if(byId('modal'))byId('modal').innerHTML='';state.modal=''}

function render(){if(!state.user)return authScreen();if(!state.profile)return profileSetup();shell()}
Object.assign(window,{state,inv,branch,imgs,go,renderView,showLogin,showSignup,signIn,signUp,logout,saveProfile,openProduct,saveProduct,closeModal,addCart,changeQty,completeSale,openImport,saveImport,openImportItem,saveImportItem,receiveImport,toggleCatalog,loadAll});
init();